# 公共配置文件
# @author <a href="https://github.com/liyupi">程序员鱼皮</a>
# @from <a href="https://yupi.icu">编程导航知识星球</a>
spring:
  application:
    name: Hzx-Open-Apis-Platform
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    # todo 取消注释开启分布式 session（须先配置 Redis）
    store-type: redis
    # 30 天过期
    timeout: 2592000
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.139.242.193:3306/hzx_apis_platform?useSSL=false&serverTimezone=UTC
    username: root
    password: hzx2001
  # Redis 配置
  # todo 需替换配置，然后取消注释
  redis:
    host: 43.139.242.193
    port: 6379
    database: 1 #配置默认访问的数据库
    connect-timeout: 5000
    lettuce:
      pool:
        # 最大连接数目: 默认是 8
        max-active: 28
        # 最大连接阻塞等待时间，默认是 -1
        max-wait: 10000ms
        # 最大空闲连接，默认是 8
        max-idle: 200
        # 最小空闲连接，默认是 0
        min-idle: 5
  # Elasticsearch 配置
  # todo 需替换配置，然后取消注释
  #  elasticsearch:
  #    uris: http://localhost:9200
  #    username: root
  #    password: 123456
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
  cloud:
    nacos:
      server-addr: 43.139.242.193:8848
      username: nacos  # Nacos 用户名
      password: nacos  # Nacos 密码
      discovery:
        namespace: f9e97085-00c9-4389-b947-0a7aef458f78
        group: SEATA_GROUP
      config:
        namespace: f9e97085-00c9-4389-b947-0a7aef458f78
        group: SEATA_GROUP
        file-extension: yaml
    alibaba:
      seata:
        tx-service-group: default
server:
  address: 0.0.0.0
  port: 8888
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
# 微信相关
wx:
  # 微信公众平台
  # todo 需替换配置
  mp:
    token: xxx
    aesKey: xxx
    appId: xxx
    secret: xxx
    config-storage:
      http-client-type: HttpClient
      key-prefix: wx
      redis:
        host: 127.0.0.1
        port: 6379
      type: Memory
  # 微信开放平台
  # todo 需替换配置
  open:
    appId: xxx
    appSecret: xxx
# 对象存储
# todo 需替换配置
cos:
  client:
    accessKey: xxx
    secretKey: xxx
    region: xxx
    bucket: xxx
# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: "接口文档"
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.jools.project.controller
jools:
  client:
    access-key: jools
    secret-key: 123456
dubbo:
  application:
    name: dubbo-springboot-demo-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://43.139.242.193:8848
    id: nacos-registry
    group: SEATA_GROUP  # 分组，注意位置
    parameters:
      namespace: f9e97085-00c9-4389-b947-0a7aef458f78  # 命名空间，注意位置
  cache:
    file: /root/.dubbo
  scan:
    base-packages: com.jools.project.service.impl.inner

# Seata 配置
seata:
  client:
    rm:
      register-timeout: 20000
  enabled: true
  application-id: Hzx-Open-Apis-Platform
  # Seta 事务组编号，用于 TC 集群名称
  tx-service-group: Hzx-Open-Apis-Platform-group
  # 开启自动代理
  enable-auto-data-source-proxy: true
  service:
    vgroup-mapping:
      Hzx-Open-Apis-Platform-group: default
    grouplist:
      default: 43.139.242.193:8091  # 确保这个 IP 和端口是正确的
    enable-degrade: false
  registry:
    type: nacos
    nacos:
      server-addr: 43.139.242.193:8848  # 修改为外部可访问的 Nacos IP
      namespace: f9e97085-00c9-4389-b947-0a7aef458f78
      group: 'SEATA_GROUP'
  config:
    type: nacos
    nacos:
      server-addr: 43.139.242.193:8848  # 修改为外部可访问的 Nacos IP
      namespace: f9e97085-00c9-4389-b947-0a7aef458f78
      group: 'SEATA_GROUP'
#debug: true

